[package]
name = "4x8matrix/console"
version = "1.2.0"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
licence = "Unlicense"
authors = ["AsynchronousMatrix <Catbob614@gmail.com>"]

description = "A Roblox resource to simplify & enhance the Roblox Console/Output"

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.lock", "wally.toml", "LICENCE", "README.md"]

[dependencies]
Signal = "sleitnick/signal@1.2.1"